### ISSUE TITLE
Request for package information failed: tunneling socket could not be established, cause=connect ETIMEDOUT (5 attempts) (ECONNRESET)

### ISSUE THREAD

**Issue by muta1231** [jspm/github#104]
i just wanted to do 
$ apm install ionic-preview ionic serve 

but this issue happened

> $apm install ionic-preview ionic serve
Installing ionic-preview to /home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/packages 
✗
Request for package information failed: tunneling socket could not be established, cause=connect ETIMEDOUT (5 attempts) (ECONNRESET)

>・apm config ls
 ; cli configs
globalconfig = "/home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.apm/.apmrc"
user-agent = "npm/2.13.3 node/v0.10.40 linux x64"
userconfig = "/home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.apmrc"
; userconfig /home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.apmrc
https-proxy = "https://my-proxy.com:8088/"
; globalconfig /home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.apm/.apmrc
cache = "/home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.apm"
; node bin location = /usr/share/atom/resources/app/apm/bin/node
; cwd = /home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp
; HOME = /home/likewise-open/FRAMGIA/kanako.muta/.atom/.node-gyp/.atom/.node-gyp
; 'npm config ls -l' to show all defaults.

>・apm --version
apm  1.9.2
npm  2.13.3
node 0.10.40
python 2.7.6
git 1.9.1

>・Ubuntu 14.04

what should i do for this??? please help me.

thank you

**Comment by guybedford** [comment]
This is jspm, not apm... Try posting there.
