### ISSUE TITLE
Bump version number to reflect updated deps

### ISSUE THREAD

**Issue by CxRes** [jspm/github#106]
Please bump version number because tag `0.13.16` depends on `rimraf: 2.3.2` which in turn depends on `minimatch 2.x` which throws the following error:
```
 minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

**Comment by guybedford** [comment]
Thanks updated in latest.

**Comment by guybedford** [comment]
(pending release)

**Comment by guybedford** [comment]
Released.
