### ISSUE TITLE
`jspm install` not working for private repo

### ISSUE THREAD

**Issue by d34th4ck3r** [jspm/github#109]
I tried using jspm to install one of our private repositories but it keeps asking me for the login credentials.

` gautambajaj@Gautams-MacBook-Pro $ ~/Codes/upstream/wp-content/themes/upstream   dev ● $ jspm registry config github`
`Would you like to set up your GitHub credentials? [yes]:yes`
     `If using two-factor authentication or to avoid using your password you can generate an access token at https://github.com/settings/tokens.`

`Enter your GitHub username or access token: $my-token$`
`Would you like to test these credentials? [yes]:yes`
`ok   GitHub authentication is working successfully.`
`ok   Registry github configured successfully.`

Notice that I have purposefully used token as we use two-factor authentication.

`gautambajaj@Gautams-MacBook-Pro $ ~/Codes/upstream/wp-content/themes/upstream   dev ● $ jspm install github:$xxx$/$repo-name$`
 `    Looking up github:$xxx$/$repo-name$`
`Username for 'https://github.com': d34th4ck3r`
`Password for 'https://d34th4ck3r@github.com':$my-password$`

`warn Error on lookup for github:wikia/ad-engine, retrying (1).`
`     Error: remote: Invalid username or password.`
`     fatal: Authentication failed for 'wikia/ad-engine.git/'`

**Comment by guybedford** [comment]
This may be related to https://github.com/jspm/github/issues/99. //cc @adamburgess @tamird

**Comment by tamird** [comment]
This doesn't look like #99 to me, since this is a private repo on Github rather than Github Enterprise.

@d34th4ck3r is the token you're using privileged? That is, does it have permission to see your private repos?

**Comment by guybedford** [comment]
This should be resolved in https://github.com/jspm/github/pull/112 now.

**Comment by guybedford** [comment]
Released.
