### ISSUE TITLE
npm package out of sync with repository

### ISSUE THREAD

**Issue by marionebl** [jspm/github#111]
Publish `0.14.11` containing https://github.com/jspm/github/commit/ed86cbcaefbbd9a5eaac22459a15c8115f4d0b4b to avoid deprecation warnings related to `rimraf@2.3.4 > glob@4.5.4 > minimatch@2.0.10`

```
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

Thank you!

**Comment by guybedford** [comment]
Thanks, yes a new release will be posted out soon.
