### ISSUE TITLE
Allow authentication using SSH

### ISSUE THREAD

**Issue by guybedford** [jspm/github#12]
We could provide an option in https://github.com/jspm/github/blob/master/github.js#L131 to select between SSH or HTTP auth when setting up GitHub credentials.

**Comment by alexch** [comment]
Here's a strong argument to support ssh: it's part of the definition of a [Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols). Why have a `github` provider when you could just have a `git` provider, like this:

      "{name}": "git:{url}@{version}"
     
e.g.

      "angular": "git:https://github.com/angular/bower-angular.git@^1.4.8"`

or

      "angular": "git:ssh://git@github.com:github.com/angular/bower-angular.git@^1.4.8" 

The latter could be used for private (ssh) repos (where the Git URL as provided by Github is `git@github.com:github.com/angular/bower-angular.git` or `git@github.com:github.com/angular/bower-angular.git`) and use the user's existing SSH config as used by `git` itself.

(And yeah, I know there's a [jspm git](https://www.npmjs.com/package/jspm-git) provider but it doesn't work right either.)

I'm new to JSPM and I've been writing setup scripts (for trying to get new developers up to speed or setting up a build box) and have found no way to run `jspm registry config github` or `jspm registry config git` in a script -- it either forces user input ("what's your password?" or "what's github's base URL?") or requires me to hackily insert code into the user's `.jspm/config` file, both of which are less than ideal.

**Comment by guybedford** [comment]
@alexch thanks for sharing your thoughts here. I think you're exactly wanting to use the `git` registry, and you are completely right that something like this should be available in core. I was hoping to merge the `git` registry into core when it reaches the right level of maturity, so if you or anyone else is interested in contributing to that project to get it to that point that would be incredibly welcome.

All jspm config can be set programatically via config commands like:

```
  jspm config registries.git.username asdf
  jspm config registries.git.password akjds
```

In addition the jspm-git endpoint could choose to check system environment variables itself, just like the jspm-github project does in https://github.com/jspm/github/blob/master/github.js#L90.

I'd love to solve these issues in user land and bring the work back into jspm core, but can't do it on my own.

**Comment by alexch** [comment]
Cool. Thanks for the suggestion to use `jspm config registries.git...` I'll try that when I'm back at work.

FWIW, I got my scripts to work by using `jspm-git` and force copying a complete `.jspm/config` file containing the following lines and then using `github-ssh:` as my provider name.

```
    "github-ssh": {
      "baseurl": "ssh://git@github.com/",
      "handler": "jspm-git"
    }
```

**Comment by guybedford** [comment]
@alexch if you're looking for that you probably just want `jspm registry export github-ssh` to generate the configuration commands for.

**Comment by sandys** [comment]
@guybedford another reason for ssh is that many "pro" js libraries are being distributed using ssh on bower. For example, https://forum.handsontable.com/t/congratulations-on-launching-hot-pro-whats-included-in-the-delivered-package/48

the instructions are

```bower install https://my.handsontable.com/handsontable/handsontable-pro.git
In this way you must provide your username:  and password that was sent to you in an activation email.

bower install git@git.handsontable.com:handsontable/handsontable-pro.git
If your team consists of many people or you just don't want to enter your login and password over and over again, then simply add your unique SSH key to the settings page and use the following Git endpoint to connect with server and download your package:
```

**Comment by jonricaurte** [comment]
@guybedford I think @alexch is right. This is has been the biggest pain point with using jspm. All I have to do for bower to use a private repo is this:

"package-name": "git@github.com:package/repo.git"

That's it, nothing else.

**Comment by guybedford** [comment]
This reliance on the github api is removed in jspm 0.17 since we deprecated release downloads.

**Comment by jonricaurte** [comment]
@guybedford I am using 0.17 and have to use jspm install github:private/repo@v1. How would I be able to go about downloading private repos on github?
