### ISSUE TITLE
Unable to jspm install Github release archive

### ISSUE THREAD

**Issue by Mobe91** [jspm/github#124]
I have created a GitHub release of `https://github.com/ordami/primeui` with tag `v4.1.15-ordami-1`. Now I am trying to install this release using `jspm install primeui=github:ordami/primeui@v4.1.15-ordami-1` but I get 
```
err  No version match found for github:ordami/primeui@v4.1.16
```
When I do `jspm install primeui=github:ordami/primeui@4.1.15-ordami-1` (without the `v`), then I get the repository checked out but not the release archive.

I am running JSPM version `0.16.53`.
What am I doing wrong?

**Comment by guybedford** [comment]
JSPM automatically removes the "v" prefix from versions, so `@4.1.16` is all that is needed to change here.
