### ISSUE TITLE
Missing release pagination handling causes wrong main entry  

### ISSUE THREAD

**Issue by ajourln** [jspm/github#131]
Package "github:twbs/bootstrap@3.3.7"

Package [override ](https://github.com/jspm/registry/blob/master/package-overrides/github/twbs/bootstrap%403.3.7.json)specifies main to be at "js/bootstrap.js"

However due to v3.3.7 falling out of the releases page https://api.github.com/repos/twbs/bootstrap/releases the correct [asset](https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip) can no longer be found. (default pagesize is 30)

Instead the [source](https://github.com/twbs/bootstrap/archive/v3.3.7.zip) for the tag v3.3.7 will be downloaded - That archive has a different folder structure (dist/js/boostrap.js) and the main entry point is now broken.

I'll create a pull request with a temporary fix (increase pagesize) and continue working on a permanent fix (loop through pages)

**Comment by ajourln** [comment]
cc @guybedford 

Is it possible to release a new version?

**Comment by guybedford** [comment]
Released in 0.13.22.
