### ISSUE TITLE
github-jspm   ...remotes.authHeader install issue with version "jspm-github": "^0.13.17",

### ISSUE THREAD

**Issue by omkarvijf41** [jspm/github#134]
Hi Team,
We are encountering issue with github-jspm import with below error
![image](https://user-images.githubusercontent.com/20302268/113002890-3cdd4280-9140-11eb-8078-0e2e98e2c98d.png)

**Comment by guybedford** [comment]
Thanks for posting, I've pushed a fix in 0.13.24.

**Comment by omkarvijf41** [comment]
> 0.13.24

Great. Thank you very much.
