### ISSUE TITLE
Install fails when using new Github token and Github Auth

### ISSUE THREAD

**Issue by yafanasiev** [jspm/github#136]
Github introduced new token formats and is actively encouraging users to switch. Current implementation does not recognize new tokens as tokens thus erroring out on installation when using Github Auth. This adds the support for the new characters in token and also the upcoming changes to token length. I have added a [PR](https://github.com/jspm/github/pull/135) with the fix for 0.13, I believe this should be also done for other versions as well.

**Comment by guybedford** [comment]
Released in 0.13.26.

**Comment by yafanasiev** [comment]
Thanks to @guybedford for the lightning fast reaction! This was an obvious blocker for us.
