### ISSUE TITLE
Large download timeouts

### ISSUE THREAD

**Issue by guybedford** [jspm/github#15]
Try `jspm install github:google/material-design-icons`. This downloads from the zip release archive.

Somehow we're stalling after extraction, but the hash info is being written so that cancelling and restarting shows it is up-to-date. This may be something in the post-processing phase, or a timeout.

**Comment by akash1810** [comment]
This issue looks to be back. Tying to install the latest `material-design-icons` (`jspm install material-design-icons`) and the following happens:

```sh
Updating registry cache...
     Looking up github:google/material-design-icons
     Downloading github:google/material-design-icons@2.0.0
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    37293 abort      ./node_modules/.bin/jspm install material-design-icons
```

**Comment by guybedford** [comment]
There is a `maxRepoSize` configuration which can be set via `jspm config registries.github maxRepoSize 100` where the size is in MB. That said, this issue looks like a machine-level memory issue. Increasing the process maxBuffer may help, which I've added in https://github.com/jspm/github/commit/2ae9643a0c33dea16aab2f2ffe78501734846dc0, will release shortly to test.

**Comment by adamduren** [comment]
I think I may have encountered a similar issue. I tried the max repo size setting but I'm not sure that's the case. Here is a log of the command and output. Any ideas?
```bash
$ jspm install npm:solc
     Looking up npm:solc
     Updating registry cache...
     Downloading npm:solc@0.3.0-1

<--- Last few GCs --->

   19515 ms: Scavenge 1406.3 (1457.6) -> 1406.3 (1457.6) MB, 23.0 / 0 ms (+ 1.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
   20641 ms: Mark-sweep 1406.3 (1457.6) -> 1406.2 (1456.6) MB, 1126.6 / 0 ms (+ 2.0 ms in 2 steps since start of marking, biggest step 1.0 ms) [last resort gc].
   21787 ms: Mark-sweep 1406.2 (1456.6) -> 1406.1 (1457.6) MB, 1145.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000118108E3AD1 <JS Object>
    1: visitBinaryExpression [D:\Users\Adam\workspace\ethereum\base\node_modules\systemjs-builder\node_modules\traceur\bin\traceur.js:~24230] [pc=000001A3787D7BFE] (this=000003744EB7BCA9 <a ParseTreeWriter with map 0000022B266FA251>,tree=00000163D34BBF61 <a BinaryExpression with map 0000022B266F7F41>)
    2: visit [D:\Users\Adam\workspace\ethereum\base\node_modules\systemjs-builder\node_modul...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

**Comment by guybedford** [comment]
@adamduren that's a memory size error, try increasing the maximum memory size allowed in Node.

**Comment by adamduren** [comment]
I tried that as well and this is what I got.
```
$ node --max-old-space-size=8000 node_modules/jspm/jspm.js install npm:solc@0.1.3
     Looking up npm:solc
     Updating registry cache...
     Downloading npm:solc@0.1.3

warn It's taking a long time to process the dependencies of npm:solc@0.1.3.
     This package may need an ignore property to indicate test or example folders for jspm to skip.


warn Timed out on build
     To increase the timeout run jspm config registries.npm.timeouts.lookup 240

err  Error building package npm:solc.

warn Installation changes not saved.
```

**Comment by guybedford** [comment]
@adamduren did you try the suggestions in the warnings? An ignore property can be added with `jspm install npm:solc@0.1.3 -o "{ignore:['test','any/other/large/unnecessary/folders']}"`
