### ISSUE TITLE
Run a `git` detection script and provide useful error on failure

### ISSUE THREAD

**Issue by guybedford** [jspm/github#24]

**Comment by guybedford** [comment]
This can be done with `which` as in https://github.com/bower/bower/blob/master/lib/core/resolvers/GitResolver.js#L18.

**Comment by guybedford** [comment]
Included in https://github.com/jspm/github/commit/d0816e67502b6b4929c773b568fc322b07b24263.

**Comment by subesokun** [comment]
Awesome, thanks for adding it :) I thought you would go with the js-git library for the lookup but this way I can add now your feature into jspm-git endpoint as well.

**Comment by guybedford** [comment]
Using `js-git` would actually be preferable, I just can't work out how!

**Comment by subesokun** [comment]
Ah ok I see. As for jspm-git a local Git installation is mandatory I can stick to that `which.sync('git')` approach as we've to use there also the `git checkout` command. Not sure if js-git can clone repositories into some local folder if it's running within the node environment and how it will be performance-wise.
