### ISSUE TITLE
Support for github enterprise?

### ISSUE THREAD

**Issue by speigg** [jspm/github#27]
https://developer.github.com/v3/enterprise/

Basically, add a configuration option allowing the hostname to be something other than `github.com`

**Comment by guybedford** [comment]
I would gladly work on this or take PRs, but haven't had a server to test it against yet.

**Comment by speigg** [comment]
Unfortunately, I can't give you access to a github enterprise server, however I got this working with https://github.com/Orbs/jspm-git ! So, problem solved ;)

**Comment by guybedford** [comment]
@speigg thanks for letting me know - this is actually probably advisable, unless support is needed for dependency look-ahead, releases or redirects which are the main extra features in jspm-github.

**Comment by speigg** [comment]
So, supporting Github Enterprise via jspm-github should actually be relatively simple, from the Github API v3:
```
All API access is over HTTPS, and accessed from the api.github.com domain (or through yourdomain.com/api/v3/ for enterprise). All data is sent and received as JSON.
```

If it provides the extra features then it would be worth it, imo. By default jspm-github can use `api.github.com`, but if the user provides an alternative domain, then it would use `<domain>/api/v3/`. I can test on with my access to a github enterprise server. Also, there is currently a bug with the Github Enterprise server that prevents cloning over http(s) with the `--depth 1` option, so if we can get this to work, it would be better than jspm-git (which at the moment only works with my fork which disables the `--depth 1.
