### ISSUE TITLE
Response too large (after it was just working)

### ISSUE THREAD

**Issue by speigg** [jspm/github#31]
This just started happening. The strange thing is that it was just working fine. 

```
$ jspm install github:mrdoob/three.js@r70
     Looking up github:mrdoob/three.js
     Updating registry cache...
     Downloading github:mrdoob/three.js@r70

err  Error downloading github:mrdoob/three.js
     Response too large.

warn Installation changes not saved.
```

The maxRepoSize is still set to 100.

**Comment by guybedford** [comment]
Well it's definitely on the theshold size - https://github.com/mrdoob/three.js/releases.

Perhaps GitHub reparsed their gzip encoding or something. Have you tried increasing the maxRepoSize? Perhaps you already had it cached somehow?

**Comment by speigg** [comment]
Even jspm install github:mrdoob/three.js@master works. 

I set maxRepoSize to 1000 and it took a long time but it finished.

**Comment by speigg** [comment]
I'm not sure how I could have had it cached

**Comment by speigg** [comment]
You're right it is caching, because if I delete them they jspm install finished very quickly now. But I'm not sure how that is related.

**Comment by speigg** [comment]
I found the cache ('~/.jspm/packages/github'), and I removed three.js@r70 from it, and from my project. I reset the maxRepoSize to default (100), and I still get this error (Response too large). I don't get this error on r69, which is larger than r70. So I have no idea what's happening... are you able to reproduce this or is it just me?

**Comment by guybedford** [comment]
@speigg the point is that the content-length of the response from GitHub is larger than 100MB. This could be for a variety of factors - note that GitHub probably uses gzip to serve responses, so that gzip compression could be the variable factor causing a difference between the perceived and actual sizes.

**Comment by speigg** [comment]
But it works for @master and @r69.. I guess I'm missing something. Unless you are saying GitHub mysteriously changed the content-length of the @r70 release in the last hour or so...

**Comment by guybedford** [comment]
Master won't compare as it's using the release archives uploaded at https://github.com/mrdoob/three.js/releases.

If you really want to investigate, try curling the tarballs and see what content-length headers you get.

**Comment by speigg** [comment]
I tried curling and the content length for r70 was ~120 MB and r69 was ~105 MB. Oh well, I guess increasing the maxRepoSize is the solution.

**Comment by guybedford** [comment]
@speigg can you work out why it is so big? Is there another release we can use like a Bower repo or npm distribution?

**Comment by guybedford** [comment]
Alternatively we can increase the default maxRepoSize to 150?

**Comment by speigg** [comment]
There isn't a separate bower repo for three.js. Anyways, I tried the npm version, and jspm is adding unnecessary dependencies to the file: buffer and process. jspm is wrapping the three.js file in the following:

```
(function(Buffer, process) {
... normal three.js file
})(require("buffer").Buffer, require("process"));
```

And then it modified my config.js by adding the following: 

```json
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.0.1"
    },
    "github:jspm/nodelibs-process@0.1.0": {
      "process": "npm:process@0.10.0"
    },
    "npm:buffer@3.0.1": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.4",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:three@0.69.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.0"
    }
```

All of which is unnecessary (threejs doesn't have any other library dependencies), so this is actually a separate bug (probably with the npm endpoint?). 

Increasing the maxRepoSize would be good, but is there a reason why we need maxRepoSize at all? I don't believe any other libraries (bower, npm, etc) impose a limit on the download size of a repository. What is the benefit in having one?

**Comment by guybedford** [comment]
@speigg perhaps we can set the default to unlimited, but I find having a value is useful to know when a download isn't worth attempting. For example, surely three.js can be used in production without needing to download all those 120MB?

**Comment by speigg** [comment]
True threejs would benefit from having a repository with just the build files, but just for the purpose of making jspm easier to get up and running with, it seems useful not to have a max download size. Once someone is ready to move to production, they can tweak things as needed.
