### ISSUE TITLE
Consider always adding `format:global` on github without an override

### ISSUE THREAD

**Issue by guybedford** [jspm/github#39]
This would be a breaking change.

The idea is that most installs from GitHub break because no package has CommonJS or AMD dependencies that properly resolve in place. We should just treat everything as a global, and it will probably give the most luck.

The next mistake users will make then is manually installing global dependencies like jQuery, but perhaps that is the lesser evil to an easier adoption path.

**Comment by subesokun** [comment]
I think same would make sense also for jspm-git. If you're going to implement it like that, then I'd go ahead and implement it in jspm-git as well :)

**Comment by timaschew** [comment]
I'm not sure about no packages on GitHub has CommonJS or AMD.
Maybe do a GitHub search for bower.json, component.json and make some tests and then we can see.

**Comment by guybedford** [comment]
Yes this will never work unfortunately.
