### ISSUE TITLE
Have rate limit errors stop and ask for credentials on the spot

### ISSUE THREAD

**Issue by guybedford** [jspm/github#46]
This improves the install experience over the full stalling we have currently.

The API issue to handle is allowing configuration to be saved at any point in time via any hook. It may be worth having a constructor option provided for "saveConfig", or something to that effect.

**Comment by AshleyGrant** [comment]
I recommend having the instructions tell the user to go to Settings/Personal Access Tokens to prod them in the right direction.

**Comment by crisptrutski** [comment]
Unfortunately it's not as simple as adding `saveConfig` to the registry:

1. We need to dequeue parallel requests to the endpoint
2. We need to escape hook timeouts

The best solution isn't clear - in my mind it would be clearer to control this process via jspm-cli rather than giving registries all this extra power.

Deferring this issue from current release to find the best solution

**Comment by guybedford** [comment]
@crisptrutski here's a suggested API:

* Any registry hook (trying to use this term over endpoint for a smaller dictionary) creates a promise rejection - `var e = new Error('GitHub rate limit has been reached')`.
* Registry marks the error as an _authentication error_ with `e.auth = true`.
* The registry system in jspm detects authentication errors, and calls the registry configure hook.
* While configuration is running, any new hooks to this registry (not others) are held up by this configure call.
* If any existing hook of this registry that were already in play complete, we allow them to complete normally.
* If any existing hook calls of this registry send back an auth error during the config call (or even after it), we then queue those on the reconfig function as well (if it is still running).
* Once the authentication is completed, we re-instantiate the registry and kick off all the queued hooks with the new instance.

Thoughts?

**Comment by crisptrutski** [comment]
Sounds like we agree on the big picture - I'll speak just to the differences though:

1. Control flow via special return values or raising "typed" exception.

  This seems a superficial choice at the size of the system. Exceptions offer some extra convenience (non local return in endpoints), and there's consistency with how "retriable issues" are handled.

2. Endpoint can specify "how" to recover in any particular case, v.s. "just call configure".

  This is a bit less superficial - seems superior to me to limit configuration prompts to those relevant. Although this "effect" could be achieved by using state on registry and adding complexity to the configuration hook, this seems clumsy and abusive. Then again, if exceptions are used for the flow control, attaching closures to exceptions seems heinous - a step too far compared to  proposal of type-marker attributes (also odd, but on rationale that code sharing an actual type between cli and endpoints would be awkward and excessive).

My understanding of your position: returning a continuation from a hook is non-familiar and unexpected to most users (yourself included).

That's a fair point - happy to proceed with your suggestion if you're happy with (2). Would lean towards still overloading configure in that case to limit prompts to authorization config in this scenario (setting a `configAuthOnly` flag on the instance before throwing)

**Comment by crisptrutski** [comment]
@guybedford limit the number of times it drops back to configuration? just once?

**Comment by guybedford** [comment]
Yes once sounds reasonable, as the configuration prompts let you test authentication anyway.
