### ISSUE TITLE
API redirects

### ISSUE THREAD

**Issue by guybedford** [jspm/github#54]
When they land - https://developer.github.com/changes/2015-04-17-preview-repository-redirects/

**Comment by adamburgess** [comment]
hey @guybedford, is this resolved? e.g. `jspm install github:6to5/6to5` seems to redirect correctly to `github:babel/babel` for me

**Comment by guybedford** [comment]
Yes that is supported, but this is a different issue - at the moment we actually send a repo HTTP request that gets the normal project page as seen by the browser, and we detect a redirect on this request to support it. Ideally we should use the proper API here which is what this is tracking.
