### ISSUE TITLE
406 error when installing private repositories from an organization

### ISSUE THREAD

**Issue by tengyifei** [jspm/github#55]
jspm version: 0.15.6
jspm-github version: 0.11.6

Have setup and tested Github credentials, and they have `repo` permission.

jspm says:
```
warn Error on download for github:<organization>/<repo-name>, retrying (1).
     Download: Bad response code 406
```

**Comment by guybedford** [comment]
Perhaps that isn't enough permissions as it will still try to use the GitHub release API to list any published releases.

Have you tried increasing the permissions?

**Comment by tengyifei** [comment]
I tried again with every single item checked, still to no avail. If I check `repo` then `public_repo` will remain unchecked. If I check `public_repo` by unselecting `repo`, jspm will report that the private repository is not found.

**Comment by tengyifei** [comment]
Relevant line could be https://github.com/jspm/github/blob/master/github.js#L565

**Comment by guybedford** [comment]
Are you perhaps able to try using `curl` against that URL directly?

**Comment by guybedford** [comment]
@tengyifei did you manage to make any progress here?

**Comment by guybedford** [comment]
@tengyifei did you say this was GitHub enterprise? The truth is we haven't had direct access to a GitHub enterprise setup to test this use case entirely, but have just relied on community contributions. Would love to sort it out if you're interested in pursuing this further.

**Comment by tengyifei** [comment]
Hey sorry for the delay. I was trying hard to reproduce this problem but it seems to have disappeared after I removed all `node_modules` and reinstalled jspm. Nonetheless when I tried to access `https://<username>:<password>@github.com/<organization>/<repo>/archive/<version>.tar.gz` Github gave me a 406 error.

```
$ wget https://<username>:<password>@github.com/<organization>/<repo>/archive/<version>.tar.gz
--2015-06-08 14:01:22--  https://<username>:<password>@github.com/<organization>/<repo>/archive/<version>.tar.gz
Resolving github.com... 192.30.252.131
Connecting to github.com|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 406 Not Acceptable
2015-06-08 14:01:22 ERROR 406: Not Acceptable.
```

I'd love to help on Github Enterprise but we are on the official Github server right now. I'll close this but will keep you posted if the problem resurfaces.

**Comment by guybedford** [comment]
Glad to hear it is working ok  now - yes private GitHub is tested and working though.
