### ISSUE TITLE
versions with a 'v' prefix don't work

### ISSUE THREAD

**Issue by timaschew** [jspm/github#56]
found out that jspm fails for this:

`jspm install github:FortAwesome/Font-Awesome@v4.2.0`

even if the git tag is __v4.2.0__ https://github.com/FortAwesome/Font-Awesome/releases

I personally don't like the __v__ prefixes, but just wanted to give a note.

`jspm install github:FortAwesome/Font-Awesome@4.2.0` works fine

**Comment by guybedford** [comment]
Yes this is by design - when converting GitHub tags into looked-up versions a `v` before a semver is removed.
