### ISSUE TITLE
Misleading error when ~/.netrc is invalid

### ISSUE THREAD

**Issue by valsteen** [jspm/github#63]
jspm-github@0.13.0
jspm@0.15.7

Just had a silly problem, I figured I should report it so it's at least documented somewhere.

```bash
% jspm registry config github

err  Registry handler`jspm-github` not installed.
```

In fact the registry is installed, but it crashed at some point because my ~/.netrc is invalid. It started with 

```
//machine localhost
```

Fixing the file or deleting it ( if you don't need it ) fixes the problem.

**Comment by guybedford** [comment]
Thanks, fixed in https://github.com/jspm/github/commit/6a4b0446878203bc60f6e69db775d0e71d4d4384.
