### ISSUE TITLE
GitHub rate limit reached on Travis CI testing

### ISSUE THREAD

**Issue by neothemachine** [jspm/github#67]
I just setup travis ci with a jspm project but github rate limit is reached: https://travis-ci.org/Reading-eScience-Centre/covjson-reader/jobs/80846112 Probably because Travis has just a few external IP addresses. This makes testing jspm libraries/projects with Travis CI complicated.

**Comment by guybedford** [comment]
Have you set up auth as in https://github.com/jspm/jspm-cli/wiki/Registries#auto-configuring-registries?

**Comment by neothemachine** [comment]
Ok, I will do that, but it's still annoying and this should somehow work out-of-the-box in the future.

**Comment by wichert** [comment]
https://github.com/jspm/jspm-cli/wiki/Registries is a 404
