### ISSUE TITLE
Support <= etc. in version ranges or display better error message

### ISSUE THREAD

**Issue by neothemachine** [jspm/github#69]
(Continuation from https://github.com/jspm/jspm-cli/issues/1172)

When using <= as version range for GitHub dependencies, the current error message is `no version match for github:mbostock/d3@<=3.5.0`. This is because <= etc. are currently not supported. The message is misleading though and makes people (me) look at the git tags and wonder why jspm doesn't find the requested version.

Support for this is not crucial at the moment, so I'd say that improving the error message would do the job.

**Comment by guybedford** [comment]
Moved to https://github.com/jspm/jspm-cli/issues/1897.
