### ISSUE TITLE
Race in the zip handling code

### ISSUE THREAD

**Issue by Gu1** [jspm/github#76]
We've been seeing some weird behaviors when installing d3.js with jspm (`jspm install d3=github:mbostock/d3@3.4.10`). The main js file (github/mbostock@3.4.10/d3.js) gets corrupted (truncated) in some cases.
We've tried to create a reproducible test case without much success. We've tried with a different d3.js version but the problem also appears

After some debugging, we think the bug is in this [piece of code](https://github.com/jspm/github/blob/master/github.js#L569-L595).
The promise is resolved as soon as yauzl emits the "close" event. But from our understanding, the close signal is emitted once "all streams created from openReadStream() have emitted their end events.", but without ensuring that all the data has actually been processed (unzipped) and wrote to the output file.
We've managed to fix the bug by rewriting the code to only resolve the promise once all the file had finished writing (.on("close") for each write stream).

**Comment by guybedford** [comment]
Thanks so much for the report here. If you're able to post a PR that would be incredibly welcome.
