### ISSUE TITLE
Set proxy in "request()" calls (?)

### ISSUE THREAD

**Issue by subesokun** [jspm/github#78]
Since recently I'm faced with a corporate firewall which behaves very strange from time to time. So far JSPM worked for me when setting the `HTTP(S)_PROXY` environment variables but today for some reason the `request` module has ignored this proxy setting. First by manually adding the proxy option in the `github.js` like

```javascript
request({ proxy: 'http://...', ... })
```
I came through the proxy. If I didn't set this option I ran always into a registry timeout. Do you think that it makes sense to read out the proxy environment variables and if set pass them into the request call?

**Comment by guybedford** [comment]
Better information flow here could well be worth it, by storing relevent proxy information in the `~/.jspm/config` file and pipeing it all through. If you're able to provide a PR along these lines it would be much appreciated.
