### ISSUE TITLE
Unable to use private github repo using access token as password

### ISSUE THREAD

**Issue by astrinxit66** [jspm/github#83]
Hi,

I'm not able to `jspm install github:<org>/<repo>` following the doc about [configuring access to a private Github](https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#private-github) and providing an access token as a password.

I granted all permission to the access token. The credentials worked successfully as stated by the configuration test and reported on github token usage history. But trying `install  github:<org>/<repo>` ends in an `repo <org>/<repo> not found!` error.

If I replace the token with my account password, everything is working, files are downloaded and installed.

Am I doing something wrong?

**Comment by guybedford** [comment]
The not found error is given by GitHub when permissions are not available through the token. Are you sure the token has access to that specific organization?

**Comment by astrinxit66** [comment]
The problem was effectively github side where I've done some changes: renew the token and bound an ssh key with the private repo. I'm not sure that the ssh binding is necessary but it works now. Thank you!
