### ISSUE TITLE
Bump graceful-fs dependency

### ISSUE THREAD

**Issue by ChALkeR** [jspm/github#84]
`graceful-fs` versions lower than v4 reevaluate native `fs` module source, which is not supported.
You should update your `graceful-fs` dependency to v4 or later. 

Tracking issue: https://github.com/nodejs/node/issues/5213.

**Comment by guybedford** [comment]
https://github.com/jspm/github/commit/91caac16a02853c4c6a3cf65cec3d6e2a8d3e6a3
