### ISSUE TITLE
401 when connecting to github locally

### ISSUE THREAD

**Issue by la-yumba** [jspm/github#85]
After a few exciting days with jspm, suddently all my `jspm install` requests fail with 401. For example:

```
$ jspm install angular-route
     Updating registry cache...
     Looking up github:angular/bower-angular-route
     Downloading github:angular/bower-angular-route@1.5.1

warn Error on getPackageConfig for github:angular/bower-angular-route
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

warn Error getting package config for github:angular/bower-angular-route.

err  Error getting package config for github:angular/bower-angular-route.

warn Installation changes not saved.
```
I did a bit of debugging and found that the following request:

```
"GET /repos/angular/bower-angular-route/contents/package.json?ref=v1.5.1 HTTP/1.1
User-Agent: jspm
Accept: application/vnd.github.v3.raw
host: api.github.com
authorization: Basic dU59U2XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXmaW5lZA==
Connection: close"
```

(token mostly hidden by me)

causes the 401 with the response `{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}`

I tried running `jspm registry config github` with valid credentials, but to no avail. I also reinstalled node (now v4.4.0) jspm (v0.16.31) and clearing caches, all to no avail.

Any help appreciated

**Comment by guybedford** [comment]
Are you using your GitHub password here or did you try generating a token? If using a token make sure you've granted it the `repo_access` permission.

**Comment by guybedford** [comment]
Sorry that's the `public_repo` permission.

**Comment by la-yumba** [comment]
The above result was after cleaning up and reinstalling jspm, so there are no explicit credentials:

```
$ jspm registry export github
jspm config registries.github.handler jspm-github
jspm config registries.github.remote https://github.jspm.io
```

when I did `jspm registry config github` with valid credentials (username and password) which are tested successfully as part of `registry config`, then jspm config is updated with my base64 encoded credentials, but still the `jspm install` fails with the same error message.

doing `jspm registry config github` with a token generated on github does not work (testing the connection fails).

**Comment by guybedford** [comment]
Try and generate an authorization token as an alternative. That may get things working, and if so, perhaps you can share what strange characters you might have in your password if that is the cause of this.

**Comment by la-yumba** [comment]
Actually it seems to make no difference whether I use no password, my github password, or an auth token, see below:

```
xxx /c/fwk-web-app (master)
$ jspm install angular-route
     Updating registry cache...
     Looking up github:angular/bower-angular-route
     Downloading github:angular/bower-angular-route@1.5.2

warn Error on getPackageConfig for github:angular/bower-angular-route
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

warn Error getting package config for github:angular/bower-angular-route.

err  Error getting package config for github:angular/bower-angular-route.

warn Installation changes not saved.

xxx /c/fwk-web-app (master)
$ jspm registry config github
Would you like to set up your GitHub credentials? [yes]:
     If using two-factor authentication or to avoid using your password you can generate an access token at https://github.com/settings/tokens. Ensure it has public_repo scope access.

Enter your GitHub username:la-yumba
Enter your GitHub password or access token:a402aXXXXXXXXXXXXXXXXXX7bfe297

Would you like to test these credentials? [yes]:
ok   GitHub authentication is working successfully.
ok   Registry github configured successfully.


xxx /c/fwk-web-app (master)
$ jspm install angular-route
     Updating registry cache...
     Looking up github:angular/bower-angular-route
     Downloading github:angular/bower-angular-route@1.5.2

warn Error on getPackageConfig for github:angular/bower-angular-route
     Unauthorized response for GitHub API.
     Use jspm registry config github to reconfigure the credentials, or update them in your ~/.netrc file.

warn Error getting package config for github:angular/bower-angular-route.

err  Error getting package config for github:angular/bower-angular-route.

warn Installation changes not saved.
```

**Comment by la-yumba** [comment]
I debugged and can give more info: 

executing `jspm registry client config github`

- my $LOCALAPPDATA/.jspm/config file is correctly updated with my encoded user:token
- I see that the request that fails is still **exactly** as before -- with the same auth header as before

```
"GET /repos/angular/bower-angular-route/contents/package.json?ref=v1.5.2 HTTP/1.1
authorization: Basic dU59U2[...]maW5lZA==
etc
```

So, after configuring the registry with my new, authorization token, the request goes out with _exactly the same authorization header as before_

authorization: Basic dU59U2[...]maW5lZA==

Shouldn't this request go out with my auth token? I would have expected so... could it be that it's not finding/reading the config correctly?

**Comment by guybedford** [comment]
I've never heard of this happening, and can't imagine how it might be possible. Since you've managed to trace it down ok, perhaps you can check that the config loaded at https://github.com/jspm/jspm-cli/blob/master/lib/global-config.js#L53 has the right credentials.

**Comment by guybedford** [comment]
(my only thought is that you may be running `jspm registry config` and `jspm install` as different users with different configs perhaps?)

**Comment by la-yumba** [comment]
The line you highlighted correctly retrieves the config, so that:

`exports.config.registries.github.auth = "bGEte..."` 

But then [here](https://github.com/jspm/github/blob/master/github.js#L446) `res.req.headers.authorization = "Basic dU59U..."`

I can't figure out where the authorization header is actually being set...

**Comment by la-yumba** [comment]
I think I found [the culprit](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) (but unfortunately not the solution)

![]<http://i67.tinypic.com/30k4ne9.png)

So, credential manager stores the pwd in a hashed format, and that's what's sent to github - not the credential stored in the jspm config. (It took me so long to realize because I was connecting to github with SSH, therefore bypassing credential manager entirely.)

I still need credential manager to connect to VSTS repos... any ideas for a fix?

**Comment by guybedford** [comment]
I really don't think that is it. As you verified the value of `dU59U2[...]maW5lZA==` comes from jspm code, and there is no interception by the crendentials manager before that point.

**Comment by la-yumba** [comment]
*Does it* come from jspm code? Where is the Authorization header set, and why is it different than what is retrieved from the config file?

The problem is clearly specific to my setup on Windows (doing the same on a linux VM everything works fine). Unfortunately reinstalling jspm, node and git has not made any difference.

On my windows machine: 

- `git clone` works
- testing the connection while `jspm registry config github` works
- `jspm install` and `jspm init` fail with 401

so, what's different about the github requests done in `registry config` and `install`?

**Comment by amenadiel** [comment]
getting the same error since yesterday using jspm@0.17-beta.49

**Comment by amenadiel** [comment]
@guybedford requesting https://github.jspm.io/ yields

> When requesting the repo name exactly, you must add the ".js" extension.
Try requesting ".js" instead.

**Comment by AmazingDesign** [comment]
I had the same problem. Solution in my case was to pass token as credentials (with `public_repo` access) not the password. And do it before the first try to `jspm install`.

**Comment by menelaosbgr** [comment]
I was getting an error as long as I was using my password. I had to change my github repository to use my token. I generated a token from: https://github.com/settings/tokens
