### ISSUE TITLE
why does use of JSPM_GITHUB_AUTH_TOKEN require public_repo?

### ISSUE THREAD

**Issue by tamird** [jspm/github#89]
According to https://developer.github.com/v3/oauth/#scopes, `public_repo`

> Grants read/write access to code, commit statuses, collaborators, and deployment statuses for public repositories and organizations. Also required for starring public repositories.

This seems excessive. Why isn't public access sufficient?

**Comment by tamird** [comment]
Looks like this is because of JSPM attempt to support username/password authentication the same way it supports API tokens. Would you consider a PR that changes this behaviour to API token only?

**Comment by guybedford** [comment]
I'm not sure what change we can do to alter this?

**Comment by guybedford** [comment]
(jspm 0.17 may need less access though)

**Comment by tamird** [comment]
It's not a matter of access - it's not like jspm needs access to _my_ public repos.

This is just a result of how the URL is being crafted. If you used https://developer.github.com/v3/#authentication (`https://api.github.com/?access_token=OAUTH-TOKEN`) you could just provide the oauth token (you wouldn't need the username at all) and no access would be needed.

**Comment by guybedford** [comment]
Ahh, well that would make life easier. PR very welcome!
